-- Indian Tourist Destinations with GPS Coordinates
-- Ready to insert into destinations table

INSERT INTO destinations (title, location, description, image, rating, reviews, price, duration, difficulty, highlights, amenities, groupSize, category, latitude, longitude) VALUES

-- HERITAGE SITES
('Taj Mahal', 'Agra, Uttar Pradesh', 'The Taj Mahal is an ivory-white marble mausoleum. A UNESCO World Heritage Site and one of the most beautiful buildings in the world, built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500&h=400&fit=crop', 4.9, 2847, 250, '4-6 hours', 'easy', 'UNESCO World Heritage Site, Marble Architecture, Sunrise View, Night Illumination', 'Restaurant, Parking, Rest Areas, Photography Allowed', 50, 'Heritage', 27.1751, 78.0421),

('Jaipur City Palace', 'Jaipur, Rajasthan', 'A magnificent blend of Rajasthani and Mughal architecture. Still partially inhabited by the royal family, it stands as a symbol of royal heritage and architectural brilliance.', 'https://images.unsplash.com/photo-1571997477406-f935529e4a96?w=500&h=400&fit=crop', 4.6, 1432, 500, '3-4 hours', 'easy', 'Royal Architecture, Museum Tour, Photography, Cultural Insights', 'Guided Tours, Museum, Cafe, Gift Shop', 60, 'Heritage', 26.9245, 75.8231),

('Hawa Mahal - Pink City', 'Jaipur, Rajasthan', 'The Hawa Mahal or Palace of Winds is a stunning five-story pink sandstone structure with 953 small windows. An iconic symbol of Jaipur and one of Indias most recognizable monuments.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1876, 200, '1-2 hours', 'easy', 'Architectural Marvel, Photography, Historical Significance, Shopping Nearby', 'Guide Available, Nearby Cafes, Parking, Washrooms', 80, 'Heritage', 26.9245, 75.8235),

('Varanasi Ghats', 'Varanasi, Uttar Pradesh', 'The holy city of Varanasi is situated on the banks of the sacred Ganges River. The ghats are lined with ancient temples and are believed to be one of the holiest pilgrimage sites in Hinduism.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 2134, 1500, '2-3 days', 'easy', 'Ganges Aarti, Boat Rides, Temple Visits, Spiritual Experience', 'Ghats Access, Boat Tours, Lodges, Restaurants', 35, 'Religious', 25.3209, 83.0093),

('Udaipur City Palace', 'Udaipur, Rajasthan', 'A romantic palace overlooking Lake Pichola, the City Palace is a stunning example of Rajasthani and Mughal architecture. Still home to the royal family, it remains one of the most iconic landmarks of Rajasthan.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=400&fit=crop', 4.8, 1765, 2500, '3-4 days', 'easy', 'Lake Cruises, Palace Tours, Sunset Views, Folk Performances', 'Lake Resorts, Boat Services, Restaurants, Heritage Hotels', 45, 'Heritage', 24.5854, 73.6822),

('Jaisalmer Fort', 'Jaisalmer, Rajasthan', 'One of the largest forts in India, Jaisalmer Fort is a magnificent structure built on a hilltop. Known for its golden sandstone architecture and desert surroundings, it offers a unique cultural experience.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1287, 600, '3-4 hours', 'easy', 'Desert Fort, Golden Architecture, Bazaars, Sunset Views', 'Fort Tours, Nearby Hotels, Restaurants, Shopping', 50, 'Heritage', 26.8940, 70.8997),

('Mysore Palace', 'Mysore, Karnataka', 'A magnificent Indo-Saracenic palace and the official residence of the royal family of Mysore. Built in 1897, it stands as a symbol of royal grandeur and architectural excellence. Illuminated beautifully in the evening.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1876, 400, '2-3 hours', 'easy', 'Royal Architecture, Palace Tour, Museum, Illuminated Evening', 'Guided Tours, Audio Guides, Cafes, Photography', 60, 'Heritage', 12.3044, 76.6553),

('Khajuraho Temples', 'Khajuraho, Madhya Pradesh', 'A group of Hindu and Jain temples known for their intricate sculptures and erotic art. Built between 950-1050 AD, they are a UNESCO World Heritage Site representing medieval Indian architecture at its finest.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 876, 600, '4-5 hours', 'easy', 'Ancient Temples, Erotic Sculptures, Medieval Architecture, Stone Carvings', 'Guided Tours, Museum, Rest Areas, Cafes', 45, 'Heritage', 24.8325, 79.9864),

('Ajanta Caves', 'Ajanta, Maharashtra', 'A series of 30 Buddhist caves carved into the rock during the 2nd century BCE. Famous for their exquisite murals and sculptures, they are a UNESCO World Heritage Site showcasing ancient Buddhist art and architecture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 945, 400, '4-5 hours', 'medium', 'Ancient Art, Buddhist Sculptures, Historical Significance, Murals', 'Guided Tours, Rest Areas, Cafes, Museum', 40, 'Heritage', 20.5506, 75.7033),

('Ellora Caves', 'Ellora, Maharashtra', 'The Ellora Caves comprise 34 Buddhist, Hindu, and Jain caves carved into a two-kilometer stretch of the Deccan Plateau. The Kailashnatha Temple is an architectural masterpiece carved from a single rock.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1098, 400, '4-5 hours', 'medium', 'Kailashnatha Temple, Ancient Sculptures, Multi-Faith Architecture, Historical Art', 'Guided Tours, Rest Areas, Cafes, Parking', 40, 'Heritage', 20.5438, 75.1761),

-- BEACHES
('Goa Beaches - Calangute', 'Goa, North Goa', 'The most popular beach in Goa with white sand, crystal clear waters, and vibrant beach shacks. Perfect for water sports, relaxation, and experiencing Goas vibrant beach culture with beach parties and nightlife.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=400&fit=crop', 4.7, 2156, 2000, '3-5 days', 'easy', 'Beach Parties, Water Sports, Seafood Cuisine, Fort Visits', 'Beach Resorts, Restaurant, Water Sports, Nightlife', 40, 'Beach', 15.5504, 73.7597),

('Goa Beaches - Baga', 'Goa, North Goa', 'A lively beach known for its vibrant water sports, shacks, and nightlife. Home to the famous Tito''s nightclub and various beach parties, making it a top choice for young travelers seeking adventure and entertainment.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=400&fit=crop', 4.6, 1654, 1800, '3-4 days', 'easy', 'Water Sports, Beach Shacks, Nightlife, Parasailing', 'Beach Huts, Restaurants, Water Sports Centers, Bars', 40, 'Beach', 15.5854, 73.7457),

('Kanyakumari', 'Kanyakumari, Tamil Nadu', 'The southern tip of India where three seas meet - the Arabian Sea, Indian Ocean, and Bay of Bengal. Known for its spectacular sunsets, spiritual significance, and the iconic Vivekananda Memorial on a rocky outcrop.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop', 4.5, 1543, 1500, '2-3 days', 'easy', 'Three Sea Meeting, Sunset Views, Vivekananda Memorial, Beach Walks', 'Beachfront Hotels, Boat Tours, Temples, Restaurants', 35, 'Beach', 8.0883, 77.5385),

('Andaman Islands - Havelock', 'Andaman and Nicobar Islands', 'A tropical paradise with pristine beaches, coral reefs, and crystal clear waters. Perfect for beach lovers, divers, and those seeking adventure with world-class scuba diving and island hopping opportunities.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop', 4.8, 1654, 4000, '4-5 days', 'easy', 'Beach Paradise, Scuba Diving, Island Hopping, Water Sports', 'Beach Resorts, Diving Centers, Boat Tours, Water Sports', 30, 'Beach', 11.9867, 93.0164),

-- NATURE & HILL STATIONS
('Kerala Backwaters', 'Kochi, Kerala', 'A network of lagoons and lakes formed by monsoon winds and sea waves. Known for scenic beauty, houseboats, and rich biodiversity. Perfect for relaxation and experiencing authentic Kerala village life from traditional houseboats.', 'https://images.unsplash.com/photo-1512343279214-4d1c16c2d008?w=500&h=400&fit=crop', 4.8, 1923, 3500, '2-3 days', 'easy', 'Houseboat Cruise, Sunset Views, Coconut Plantations, Bird Watching', 'Houseboat Stay, Restaurant, Fishing Tours, Ayurveda Spa', 30, 'Nature', 9.9312, 76.2673),

('Munnar Tea Plantations', 'Munnar, Kerala', 'A picturesque hill station known for tea plantations, mist-covered mountains, and misty mornings. Perfect destination for nature lovers and adventure seekers seeking tranquility amidst rolling green tea gardens and mountain vistas.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1543, 2000, '2-3 days', 'easy', 'Tea Plantation Tours, Mountain Trekking, Scenic Views, Local Cuisine', 'Tea Estate Stays, Guided Tours, Restaurants, Trekking Guides', 25, 'Nature', 10.1809, 76.9604),

('Darjeeling', 'Darjeeling, West Bengal', 'Known as the Queen of the Hills, Darjeeling offers breathtaking views of Kanchenjunga peak, lush green tea gardens, and charming colonial ambiance. The toy train ride is a must-do experience through misty mountains and tea estates.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1432, 2200, '3-4 days', 'easy', 'Toy Train Ride, Tea Gardens, Kanchenjunga View, Local Markets', 'Hill Resorts, Tea Tours, Restaurants, Train Rides', 30, 'Nature', 27.0410, 88.2663),

('Ooty', 'Ooty, Tamil Nadu', 'Nestled in the Nilgiri Hills, Ooty is a popular hill station offering scenic beauty, botanical gardens, and cool climate. Ideal destination for relaxation and rejuvenation surrounded by pine forests and serene lakes.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1287, 1800, '2-3 days', 'easy', 'Botanical Gardens, Mountain Trains, Lake Cruises, Scenic Drives', 'Hill Resorts, Toy Train, Boat Rides, Hill Cafes', 35, 'Nature', 11.4102, 76.6955),

('Kodaikanal', 'Kodaikanal, Tamil Nadu', 'The Princess of Hill Stations, Kodaikanal is a picturesque hill station surrounded by lakes, forests, and mountains. Known for cool climate, natural beauty, and adventure activities amidst pristine wilderness.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1543, 2000, '3-4 days', 'easy', 'Lake Walks, Trekking, Scenic Viewpoints, Local Handicrafts', 'Hill Resorts, Lake Tours, Restaurants, Handicraft Shops', 30, 'Nature', 10.2381, 77.4892),

('Gangtok', 'Gangtok, Sikkim', 'The capital of Sikkim, a scenic hill station surrounded by mountains and often called the Switzerland of India. Known for pleasant weather, natural beauty, Buddhist monasteries, and colorful flower gardens.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1432, 2200, '3-4 days', 'easy', 'Mountain Views, Buddhist Monasteries, Flower Gardens, Local Culture', 'Hill Resorts, Mountain Tours, Restaurants, Monasteries', 30, 'Nature', 27.5330, 88.6141),

('Nainital', 'Nainital, Uttarakhand', 'A beautiful lake district in the mountains surrounded by pine forests, offering panoramic views. Known for pristine lakes, adventure activities, and serene natural beauty perfect for family vacations and nature lovers.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1432, 1600, '2-3 days', 'easy', 'Lake Cruises, Mountain Trekking, Scenic Drives, Local Markets', 'Lakeside Resorts, Boat Tours, Restaurants, Trekking Guides', 30, 'Nature', 29.3803, 79.4504),

-- ADVENTURE
('Himalayan Treks', 'Himachal Pradesh & Uttarakhand', 'The Himalayas offer breathtaking trekking routes from snow-covered peaks to lush green valleys. Experience raw nature at its finest with high altitude trails, mountain passes, and pristine wilderness perfect for adventure enthusiasts.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.9, 1654, 4500, '5-7 days', 'hard', 'Snow Peaks, Alpine Meadows, Mountain Views, Wildlife', 'Mountain Lodges, Guides Available, Camping, Local Cuisine', 15, 'Adventure', 32.2431, 77.1771),

('Manali', 'Manali, Himachal Pradesh', 'A popular hill station known for scenic beauty, adventure activities, and pleasant climate. Surrounded by mountains, forests, and rivers, perfect for adventure and nature lovers seeking outdoor thrills and mountain escapade.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1876, 2000, '3-4 days', 'medium', 'Adventure Sports, Trekking, River Rafting, Mountain Views', 'Adventure Centers, Hill Resorts, Restaurants, Guides', 25, 'Adventure', 32.2406, 77.1895),

('Shimla', 'Shimla, Himachal Pradesh', 'The capital of Himachal Pradesh, a charming hill station with colonial architecture, scenic beauty, and adventure activities. Known for pleasant weather, panoramic mountain views, and Mall Road shopping experience.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1543, 1800, '2-3 days', 'easy', 'Colonial Architecture, Ridge Walk, Mall Road Shopping, Mountain Views', 'Hill Resorts, Restaurants, Shopping, Cable Car', 35, 'Nature', 31.7975, 77.1597),

('Kasol', 'Kasol, Himachal Pradesh', 'A scenic village nestled in the Parvati Valley known for scenic beauty, cafes, and adventure activities. Popular with backpackers and nature lovers offering riverside walks, trekking, and vibrant local culture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1287, 1200, '2-3 days', 'easy', 'Valley Views, Trekking, Riverside Cafes, Local Culture', 'Backpacker Hostels, Cafes, Trekking Guides, River Activities', 20, 'Nature', 31.9875, 77.5023),

('Spiti Valley', 'Spiti, Himachal Pradesh', 'A remote and rugged mountain valley with breathtaking landscapes, ancient Buddhist monasteries, and unique culture. Perfect for adventurous travelers seeking pristine wilderness, high mountain passes, and authentic Tibetan culture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.9, 765, 4000, '5-7 days', 'hard', 'Remote Mountains, Buddhist Monasteries, High Passes, Wilderness', 'Mountain Lodges, Jeep Tours, Local Guides, Basic Facilities', 12, 'Adventure', 31.9522, 78.0304),

('Rishikesh', 'Rishikesh, Uttarakhand', 'The yoga capital of the world, a spiritual destination on the banks of the Ganges. Known for ashrams, yoga retreats, and adventure activities like river rafting offering perfect blend of spirituality and adventure.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1876, 1500, '3-5 days', 'easy', 'Yoga Ashrams, Spiritual Retreats, River Rafting, Ghats & Temples', 'Yoga Centers, Ashram Stays, Restaurants, River Tours', 25, 'Religious', 30.0886, 78.2679),

-- WILDLIFE & NATURE RESERVES
('Bandhavgarh National Park', 'Bandhavgarh, Madhya Pradesh', 'Known for high tiger population, Bandhavgarh is one of Indias premier wildlife destinations. Dense forests and scenic landscapes make it perfect for wildlife enthusiasts seeking authentic safari experience and tiger spotting.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.8, 1098, 3000, '2-3 days', 'easy', 'Tiger Safari, Wildlife Viewing, Jeep Tours, Nature Photography', 'Safari Lodges, Jeep Safaris, Guides, Naturalist Tours', 15, 'Adventure', 23.9203, 81.5099),

('Ranthambore National Park', 'Ranthambore, Rajasthan', 'Home to Bengal tigers and other wildlife, Ranthambore is one of Indias most visited national parks. The historic Ranthambore Fort overlooks the park adding to its charm and historical significance.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1654, 2800, '2-3 days', 'easy', 'Tiger Safaris, Wildlife Photography, Fort Ruins, Jeep Tours', 'Safari Lodges, Jeep Safaris, Expert Guides, Photography Tours', 15, 'Adventure', 25.8847, 76.5033),

('Jim Corbett National Park', 'Jim Corbett, Uttarakhand', 'Indias first national park, famous for tiger conservation and diverse wildlife. Situated in the foothills of the Himalayas with riverine vegetation and scenic trails perfect for safari and nature walks.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 987, 2500, '2-3 days', 'easy', 'Tiger Sightings, Wildlife Tours, River Valleys, Birdwatching', 'Resort Stays, Jeep Safari, Expert Guides, Nature Walks', 20, 'Adventure', 29.2275, 79.1431),

-- CULTURAL & FESTIVALS
('Pushkar Fair', 'Pushkar, Rajasthan', 'One of the worlds largest cattle fairs, the Pushkar Fair is a colorful and vibrant annual event. A unique blend of commerce, culture, and spirituality with camel races, folk performances, and traditional commerce.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1298, 2000, '2-3 days', 'easy', 'Cattle Fair, Camel Rides, Cultural Events, Local Crafts', 'Fair Ground Stays, Camel Rides, Performances, Food Stalls', 50, 'Cultural', 26.4859, 74.5549),

('Hampi Ruins', 'Hampi, Karnataka', 'The ruins of Hampi are a testament to the glory of the Vijayanagara Empire. Spread over a vast area with temples, palaces, and monuments carved from granite boulders, Hampi is a UNESCO World Heritage Site.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1098, 500, '2-3 days', 'medium', 'Ancient Temples, Royal Structures, Boulder Landscape, Historical Art', 'Guided Tours, Rest Areas, Cafes, Local Guides', 35, 'Heritage', 15.3350, 76.4639),

('Nalanda University Ruins', 'Nalanda, Bihar', 'One of the oldest universities in the world, Nalanda was a center of learning for over 700 years. The ruins showcase the intellectual heritage and architectural achievements of ancient Buddhist India and monastic education.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.4, 654, 500, '3-4 hours', 'easy', 'Ancient University, Archaeological Ruins, Buddhist Heritage, Historical Significance', 'Museum, Guided Tours, Rest Areas, Cafes', 40, 'Heritage', 25.1419, 85.7820),

-- DESERT EXPERIENCES
('Thar Desert Safari - Jaisalmer', 'Jaisalmer, Rajasthan', 'Experience the vast golden dunes of the Thar Desert. A camel safari followed by desert camp with traditional Rajasthani culture, folk music, and dance under the stars is an unforgettable desert experience.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1654, 1500, '1 day', 'easy', 'Camel Safari, Desert Sunset, Folk Performances, Desert Camp', 'Camel Rides, Camp Stay, Traditional Meals, Folk Shows', 20, 'Adventure', 26.8940, 70.8997),

('Khimsar Sand Dunes', 'Khimsar, Rajasthan', 'A beautiful village known for sand dunes and authentic desert charm. Perfect for experiencing authentic desert life and participating in camel safaris through rippling dunes and traditional Rajasthani village culture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.4, 876, 1200, '2-3 days', 'easy', 'Sand Dunes, Camel Safari, Desert Village, Sunset Rides', 'Desert Camps, Camel Rides, Traditional Meals, Folk Programs', 20, 'Adventure', 27.8203, 72.7366),

-- PILGRIMAGE
('Badrinath Temple', 'Badrinath, Uttarakhand', 'One of the most sacred pilgrimage sites for Hindus, Badrinath Temple is located in the northern Himalayas. Dedicated to Lord Vishnu, it is one of the four Dhams that all Hindu devotees aspire to visit.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.8, 1654, 2500, '2-3 days', 'medium', 'Sacred Temple, Himalayan Beauty, Spiritual Experience, Mountain Views', 'Temple Accommodation, Restaurants, Guides, Rest Areas', 30, 'Religious', 30.7496, 79.4994),

('Kedarnath Temple', 'Kedarnath, Uttarakhand', 'An ancient Hindu temple dedicated to Lord Shiva, Kedarnath is one of the most sacred pilgrimage sites. Located at high altitude in the Himalayas, it offers spiritual solace and scenic mountain beauty.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 1432, 2000, '2-3 days', 'medium', 'Sacred Temple, Mountain Pilgrimage, Spiritual Journey, Scenic Views', 'Temple Accommodation, Restaurants, Guides, Rest Areas', 30, 'Religious', 30.7353, 79.2306),

('Meenakshi Temple', 'Madurai, Tamil Nadu', 'An ancient Hindu temple dedicated to Goddess Meenakshi, one of South Indias most important pilgrimage destinations. Famous for its intricate gopurams and vibrant temple culture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1543, 1200, '2-3 days', 'easy', 'Ancient Temple, Intricate Architecture, Religious Significance, Temple Traditions', 'Temple Hotels, Restaurants, Guides, Nearby Markets', 40, 'Religious', 9.9252, 78.1198),

('Golden Temple', 'Amritsar, Punjab', 'The holiest shrine of Sikhism, the Golden Temple is one of the most beautiful temples in India. Located in the holy city of Amritsar, it attracts millions of devotees and visitors from around the world seeking spiritual peace.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.8, 2134, 800, '1-2 days', 'easy', 'Golden Architecture, Spiritual Significance, Free Langar, Pilgrimage', 'Temple Accommodation, Langar Service, Restaurants, Guides', 60, 'Religious', 31.6200, 74.8765),

-- MODERN ATTRACTIONS
('Gateway of India', 'Mumbai, Maharashtra', 'An iconic monument and symbol of Mumbai, the Gateway of India overlooks the Arabian Sea. Built during the British Raj, it stands as a testament to colonial architecture and offers views of the harbor and coastal beauty.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.5, 1876, 800, '2-3 hours', 'easy', 'Iconic Monument, Waterfront Views, Photography, Architecture', 'Nearby Cafes, Restaurants, Boat Tours, Shopping', 100, 'Heritage', 18.9220, 72.8347),

('India Gate', 'New Delhi, Delhi', 'A war memorial built to honor Indian soldiers who died in World War I. Located in the heart of Delhi, India Gate is one of the most recognizable monuments in India and a gathering place for locals and tourists.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.4, 1654, 600, '2-3 hours', 'easy', 'War Memorial, Architectural Beauty, City Views, Street Food', 'Parks Nearby, Restaurants, Shopping Centers, Cafes', 100, 'Heritage', 28.6129, 77.2295),

('Red Fort', 'New Delhi, Delhi', 'A massive fort built by Mughal emperor Shah Jahan, the Red Fort served as the residence of the Mughal emperors. It is now a UNESCO World Heritage Site and stands as a symbol of Indian independence and architectural grandeur.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 1432, 700, '3-4 hours', 'easy', 'Mughal Architecture, Historical Significance, Museum, Sound & Light Show', 'Guided Tours, Restaurants, Cafes, Photography', 80, 'Heritage', 28.6562, 77.2410),

-- SCENIC VIEWPOINTS
('Nubra Valley', 'Ladakh', 'A scenic valley in Ladakh known for sand dunes, Bactrian camels, and breathtaking mountain views. Perfect for adventure seekers and those wanting to experience the unique Ladakhi landscape and culture.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.7, 987, 3500, '3-4 days', 'medium', 'Sand Dunes, Camel Rides, Mountain Views, Tibetan Culture', 'Adventure Camps, Local Guides, Guesthouses, Local Cuisine', 15, 'Adventure', 34.5395, 77.5577),

('Pangong Lake', 'Ladakh', 'A high-altitude glacial lake known for its stunning blue waters and changing colors. Straddling the India-China border, Pangong Lake offers breathtaking views of snow-capped mountains and a unique travel experience.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.8, 1654, 3200, '2-3 days', 'medium', 'Alpine Lake, Color-Changing Waters, Mountain Views, Border Beauty', 'Tourist Camps, Local Guides, Basic Facilities, Photography', 20, 'Nature', 33.7900, 78.6400),

('Khardung La Pass', 'Ladakh', 'One of the highest motorable passes in the world, Khardung La offers panoramic views of the Himalayas and Indus Valley. A must-visit for adventure seekers and those wanting to experience extreme altitude.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=400&fit=crop', 4.6, 876, 2000, '1 day', 'hard', 'Highest Pass, Mountain Views, Adrenaline Rush, Breathtaking Scenery', 'Adventure Tours, Guide Services, Basic Facilities', 10, 'Adventure', 34.2667, 77.5833),

-- WATER SPORTS & ISLANDS
('Lakshadweep Islands', 'Lakshadweep', 'A stunning archipelago of 36 islands with white sand beaches, turquoise waters, and coral reefs. A hidden gem for those seeking an exclusive island experience away from crowds with pristine natural beauty.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop', 4.9, 876, 5000, '4-5 days', 'easy', 'Private Beaches, Snorkeling, Coral Reefs, Island Isolation', 'Island Resorts, Water Sports, Snorkeling Gear, Local Cuisine', 20, 'Beach', 10.5667, 72.5417),

('Havelock Island', 'Andaman Islands', 'Known for Radhanagar Beach, one of Indias most beautiful beaches. Perfect for scuba diving, snorkeling, water sports, and experiencing pristine tropical island life with clear waters and marine biodiversity.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop', 4.8, 1432, 3800, '3-4 days', 'easy', 'Best Beaches, Scuba Diving, Snorkeling, Island Hopping', 'Beach Resorts, Diving Schools, Water Sports, Local Restaurants', 25, 'Beach', 11.9867, 93.0164);
