import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/destination_model.dart';
import '../providers/destination_provider.dart';
import '../utils/app_constants.dart';

class AdminDashboardScreen extends StatefulWidget {
  const AdminDashboardScreen({Key? key}) : super(key: key);

  @override
  State<AdminDashboardScreen> createState() => _AdminDashboardScreenState();
}

class _AdminDashboardScreenState extends State<AdminDashboardScreen> {
  int _currentStep = 0;
  bool _isSubmitting = false;

  // Basic Info
  final _titleController = TextEditingController();
  final _locationController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _imageUrlController = TextEditingController();
  final _categoryController = TextEditingController();

  // Pricing & Details
  final _priceController = TextEditingController();
  final _durationController = TextEditingController();
  final _difficultyController = TextEditingController();
  final _ratingController = TextEditingController();
  final _reviewsController = TextEditingController();

  // Location Coordinates
  final _latitudeController = TextEditingController();
  final _longitudeController = TextEditingController();

  // Collections
  final _highlightsController = TextEditingController();
  final _amenitiesController = TextEditingController();
  final _groupSizeController = TextEditingController();

  List<String> _highlights = [];
  List<String> _amenities = [];

  final List<String> _categories = [
    'Beaches',
    'Mountains',
    'Adventure',
    'Nature',
    'Heritage',
    'Culture',
    'Food',
    'Shopping',
    'Nightlife',
    'Wellness',
    'Art',
    'Photography',
  ];

  @override
  void dispose() {
    _titleController.dispose();
    _locationController.dispose();
    _descriptionController.dispose();
    _imageUrlController.dispose();
    _categoryController.dispose();
    _priceController.dispose();
    _durationController.dispose();
    _difficultyController.dispose();
    _ratingController.dispose();
    _reviewsController.dispose();
    _latitudeController.dispose();
    _longitudeController.dispose();
    _highlightsController.dispose();
    _amenitiesController.dispose();
    _groupSizeController.dispose();
    super.dispose();
  }

  void _addHighlight() {
    if (_highlightsController.text.isNotEmpty) {
      setState(() {
        _highlights.add(_highlightsController.text);
        _highlightsController.clear();
      });
    }
  }

  void _addAmenity() {
    if (_amenitiesController.text.isNotEmpty) {
      setState(() {
        _amenities.add(_amenitiesController.text);
        _amenitiesController.clear();
      });
    }
  }

  Future<void> _submitDestination() async {
    if (_titleController.text.isEmpty ||
        _locationController.text.isEmpty ||
        _categoryController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please fill in required fields'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final destination = Destination(
        id: '', // Will be generated by Supabase
        title: _titleController.text,
        location: _locationController.text,
        description: _descriptionController.text,
        image: _imageUrlController.text,
        category: _categoryController.text,
        rating: double.tryParse(_ratingController.text) ?? 0.0,
        reviews: int.tryParse(_reviewsController.text) ?? 0,
        price: double.tryParse(_priceController.text) ?? 0,
        duration: int.tryParse(_durationController.text) ?? 1,
        difficulty: _difficultyController.text.isEmpty ? 'Moderate' : _difficultyController.text,
        highlights: _highlights.isNotEmpty ? _highlights : ['Beautiful destination'],
        amenities: _amenities.isNotEmpty ? _amenities : ['Parking', 'Rest Areas'],
        groupSize: int.tryParse(_groupSizeController.text) ?? 50,
        latitude: double.tryParse(_latitudeController.text) ?? 0.0,
        longitude: double.tryParse(_longitudeController.text) ?? 0.0,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Save to Supabase through provider
      final provider = context.read<DestinationProvider>();
      await provider.addDestination(destination);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Destination added successfully!'),
            backgroundColor: AppColors.success,
          ),
        );

        // Reset form
        _resetForm();
        setState(() {
          _currentStep = 0;
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  void _resetForm() {
    _titleController.clear();
    _locationController.clear();
    _descriptionController.clear();
    _imageUrlController.clear();
    _categoryController.clear();
    _priceController.clear();
    _durationController.clear();
    _difficultyController.clear();
    _ratingController.clear();
    _reviewsController.clear();
    _latitudeController.clear();
    _longitudeController.clear();
    _highlightsController.clear();
    _amenitiesController.clear();
    _groupSizeController.clear();
    _highlights.clear();
    _amenities.clear();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Admin Dashboard'),
        backgroundColor: AppColors.surface,
        foregroundColor: AppColors.textPrimary,
      ),
      body: Stepper(
        currentStep: _currentStep,
        onStepContinue: () {
          if (_currentStep < 2) {
            setState(() {
              _currentStep += 1;
            });
          } else {
            _submitDestination();
          }
        },
        onStepCancel: () {
          if (_currentStep > 0) {
            setState(() {
              _currentStep -= 1;
            });
          }
        },
        steps: [
          // Step 1: Basic Information
          Step(
            title: const Text('Basic Information'),
            isActive: _currentStep >= 0,
            content: SingleChildScrollView(
              child: Column(
                children: [
                  _buildTextField(
                    controller: _titleController,
                    label: 'Destination Title *',
                    hint: 'e.g., Taj Mahal',
                  ),
                  const SizedBox(height: AppSpacing.md),
                  _buildTextField(
                    controller: _locationController,
                    label: 'Location *',
                    hint: 'e.g., Agra, Uttar Pradesh',
                  ),
                  const SizedBox(height: AppSpacing.md),
                  _buildDropdown(
                    label: 'Category *',
                    value: _categoryController.text.isEmpty ? null : _categoryController.text,
                    items: _categories,
                    onChanged: (value) {
                      setState(() {
                        _categoryController.text = value ?? '';
                      });
                    },
                  ),
                  const SizedBox(height: AppSpacing.md),
                  _buildTextField(
                    controller: _imageUrlController,
                    label: 'Image URL',
                    hint: 'https://...',
                    maxLines: 2,
                  ),
                  const SizedBox(height: AppSpacing.md),
                  _buildTextField(
                    controller: _descriptionController,
                    label: 'Description',
                    hint: 'Detailed description...',
                    maxLines: 4,
                  ),
                ],
              ),
            ),
          ),
          // Step 2: Details & Pricing
          Step(
            title: const Text('Details & Pricing'),
            isActive: _currentStep >= 1,
            content: SingleChildScrollView(
              child: Column(
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _priceController,
                          label: 'Price (₹)',
                          hint: '5000',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                      const SizedBox(width: AppSpacing.md),
                      Expanded(
                        child: _buildTextField(
                          controller: _durationController,
                          label: 'Duration (days)',
                          hint: '3',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.md),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _ratingController,
                          label: 'Rating (0-5)',
                          hint: '4.5',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                      const SizedBox(width: AppSpacing.md),
                      Expanded(
                        child: _buildTextField(
                          controller: _reviewsController,
                          label: 'Reviews Count',
                          hint: '150',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.md),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _difficultyController,
                          label: 'Difficulty',
                          hint: 'Easy/Moderate/Hard',
                        ),
                      ),
                      const SizedBox(width: AppSpacing.md),
                      Expanded(
                        child: _buildTextField(
                          controller: _groupSizeController,
                          label: 'Group Size',
                          hint: '50',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
          // Step 3: Highlights, Amenities & Coordinates
          Step(
            title: const Text('Additional Info'),
            isActive: _currentStep >= 2,
            content: SingleChildScrollView(
              child: Column(
                children: [
                  // Highlights
                  const Text(
                    'Highlights',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _highlightsController,
                          label: 'Add Highlight',
                          hint: 'e.g., UNESCO World Heritage Site',
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      IconButton(
                        onPressed: _addHighlight,
                        icon: const Icon(Icons.add, color: AppColors.primary),
                      ),
                    ],
                  ),
                  if (_highlights.isNotEmpty) ...[
                    const SizedBox(height: AppSpacing.md),
                    Wrap(
                      spacing: AppSpacing.sm,
                      children: _highlights
                          .asMap()
                          .entries
                          .map(
                            (entry) => Chip(
                              label: Text(entry.value),
                              onDeleted: () {
                                setState(() {
                                  _highlights.removeAt(entry.key);
                                });
                              },
                              backgroundColor: AppColors.surfaceAlt,
                            ),
                          )
                          .toList(),
                    ),
                  ],
                  const SizedBox(height: AppSpacing.lg),
                  // Amenities
                  const Text(
                    'Amenities',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _amenitiesController,
                          label: 'Add Amenity',
                          hint: 'e.g., Restaurant, Parking',
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      IconButton(
                        onPressed: _addAmenity,
                        icon: const Icon(Icons.add, color: AppColors.primary),
                      ),
                    ],
                  ),
                  if (_amenities.isNotEmpty) ...[
                    const SizedBox(height: AppSpacing.md),
                    Wrap(
                      spacing: AppSpacing.sm,
                      children: _amenities
                          .asMap()
                          .entries
                          .map(
                            (entry) => Chip(
                              label: Text(entry.value),
                              onDeleted: () {
                                setState(() {
                                  _amenities.removeAt(entry.key);
                                });
                              },
                              backgroundColor: AppColors.surfaceAlt,
                            ),
                          )
                          .toList(),
                    ),
                  ],
                  const SizedBox(height: AppSpacing.lg),
                  // Coordinates
                  const Text(
                    'Location Coordinates',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: AppSpacing.md),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTextField(
                          controller: _latitudeController,
                          label: 'Latitude',
                          hint: '27.1751',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                      const SizedBox(width: AppSpacing.md),
                      Expanded(
                        child: _buildTextField(
                          controller: _longitudeController,
                          label: 'Longitude',
                          hint: '78.0421',
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: _currentStep == 2
          ? FloatingActionButton.extended(
              onPressed: _isSubmitting ? null : _submitDestination,
              backgroundColor: _isSubmitting ? AppColors.textHint : AppColors.primary,
              label: _isSubmitting
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : const Text('Add Destination'),
              icon: const Icon(Icons.check),
            )
          : null,
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    int maxLines = 1,
    TextInputType keyboardType = TextInputType.text,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.textPrimary,
          ),
        ),
        const SizedBox(height: AppSpacing.xs),
        TextField(
          controller: controller,
          keyboardType: keyboardType,
          maxLines: maxLines,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: const TextStyle(color: AppColors.textHint),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppRadius.md),
              borderSide: const BorderSide(color: AppColors.border),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.md,
              vertical: AppSpacing.md,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String label,
    required String? value,
    required List<String> items,
    required Function(String?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.textPrimary,
          ),
        ),
        const SizedBox(height: AppSpacing.xs),
        DropdownButtonFormField<String>(
          value: value,
          items: items
              .map((item) => DropdownMenuItem(value: item, child: Text(item)))
              .toList(),
          onChanged: onChanged,
          decoration: InputDecoration(
            hintText: 'Select category',
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppRadius.md),
              borderSide: const BorderSide(color: AppColors.border),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: AppSpacing.md,
              vertical: AppSpacing.md,
            ),
          ),
        ),
      ],
    );
  }
}
